### ISSUE TITLE
Missing icons for "View as" buttons

### ISSUE THREAD

**Issue by MichaIng** [raspberrypi-ui/pcmanfm-buster#2]
The PCManFM build from the RPi repository has an additional option that enables an additional set of buttons, added with this commit to the Buster branch: https://github.com/raspberrypi-ui/pcmanfm-buster/commit/89850963227503e7ad832d0fd0376c04e174d601
![settings](https://user-images.githubusercontent.com/28480705/92950705-6614da80-f45d-11ea-8d77-e26d3556b0b5.png)
This setting is enabled by default and it does not exist on Debian's build.

Those icons allow to switch the current directory content view (details, list, icons, thumbnails) and one that allows to open a new PCManFM window. The problem is, as this is no upstream or Debian default, the default LXDE icon sets that are pulled as dependency with LXDE which pulls PCManFM as default file manager, do not serve icons for those additional, by default enabled buttons.

The result is that, if one simply installs `lxde` on an RPi with official kernel/firmware APT repository applied, it looks like there is something wrong or missing:
![pcmanfm](https://user-images.githubusercontent.com/28480705/92951186-4500b980-f45e-11ea-9e38-98a8267caef7.png)

Solutions are either to disable those additional buttons (by unsetting the above setting) to revert to the default upstream/Debian appearance, or install one of the icon themes that are made for the RPi desktop and shipped only by the RPi APT repository, e.g. `rpd-icons` or `pixflat-icons`, but both is not something obvious and the first impression of a bug or broken PCManFM stays.

Usually I would say, if one does not want the RPi desktop (i.e. `raspberrypi-ui-mods`), simply do not install any LXDE or desktop-related packages from the RPi repository, but since Buster the UI parts and essential kernel/bootloader/firmware parts are placed in the same component, hence complicated APT preferences are required to exclude only the UI packages or include the essentials only + all their dependencies. Furthermore, for some reason on RPi the Debian PCManFM package leads to an instantly crashing PCManFM without any error message, even when taking care to install each and every UI/desktop/lxde related package from Debian repo as well.

I know this must have minor priority, but I think installing `lxde` on an RPi, even with official Raspberry Pi OS Lite image, is not a very uncommon step and hence I would appreciate if the first impression of the desktop would be as nice as on Debian with any other machine. Not sure about a good solution. Probably those additional icons could be hidden by default, or the RPi repo `pcmanfm` could pull the default RPi desktop icon theme as dependency, although it needs to be enabled as well. An own `lxde` package is too much for only this one reason. Perhaps someone has a good idea how to make this situation better.
___________
**NB: On Stretch the issue is the same. We did workaround it there by installing the `pcmanfm` from the Debian repository instead, which works just fine, but since Buster, as said, this one crashes on RPi.**

**Comment by spl237** [comment]
There are numerous ways you can fix this - install an icon set with those icons, like the one we provide, or disable that option in PCManFM, to name the two most obvious.

For us to fix it would require us to upstream a large amount of Pi-specific code which has diverged significantly from the original PCManFM code, which will be time-consuming and possibly not even accepted by the developers anyway.

If you have a crashing PCManFM, it is almost certainly due to it not being used with the correct version of libfm, which provides the underlying functionality. These two packages should really be merged, as inconsistencies between them cause all sorts of problems - for this reason we now have an explicit dependency between the versions of each we ship.

**Comment by MichaIng** [comment]
> There are numerous trivial ways you can fix this - install an icon set with those icons, like the one we provide, or disable that option in PCManFM, to name the two most obvious.

Thanks for repeating the two solutions I wrote above 😉, but to find those is not an obvious/trivial thing. For years we had a workaround and multiple new investigation attempts while nobody even recognised that those are additional buttons, to then find those solutions. So the average users simply sees a bug where none really is.

> There are not enough Pi users running unmodified LXDE for this to be a worthwhile use of our time.

Sad to hear and of course I'm not sure if this is true and how you evaluate, but I was not expecting that you invest much time for this and even try to merge the additional code upstream, I was more aiming to at least bring this to your attention and hoping that someone has a simple creative solution so that `apt install lxde` on RPi leads to a flawless experience OOTB 😉.

> If you have a crashing PCManFM, it is almost certainly due to it not being used with the correct version of libfm, which provides the underlying functionality.

Many thanks for this info, indeed I might have missed that (no lx/x prefix), will try it immediately 👍.
I guess it's `libfm4` + `libfm-gtk4` then.

> for this reason we now have an explicit dependency between the versions of each we ship.

I just see it in the control files. As long as there is any use for this library elsewhere, I guess they cannot be merged. E.g. lxpanel depends on those two libfm packages as well but not on pcmanfm and reasonably using. Since lxde-core depends on pcmanfm, I'm not sure if there is any reasonable use for lxpanel in another environment, but just as an example 😉.

**Comment by kashifsmalik** [comment]
I know this thread is closed at the time of posting this, but wanted to share that I am experiencing the same scenario of missing icons in PCManFM. My case is that I use RPi as headless file server with files accessed through Samba or SFTP. Sometimes a scenario occurs whereby a GUI-based interaction directly on the RPi is more intuitive and quick. So, I installed PCManFM package and sat up X forwarding on the client machine. This way, launching PCManFM from console results in a GUI loading on the client. PCManFM behaves as expected, with the exception of missing toolbar icons (as given in original post). I am not interested in full-blown desktop environment, so do not want to venture into setting up LXDE.

**Comment by spl237** [comment]
If you don't install the full desktop environment, you won't get the relevant icon and theme packages. PCManFM is only intended to be used as part of LXDE, not on its own.

**Comment by MichaIng** [comment]
If you install recommendations together with APT packages, `pcmanfm` (at least the Raspbian/Debian build) pulls an icon theme automatically: https://packages.debian.org/buster/pcmanfm

Otherwise do it manually, e.g.: `apt install lxde-icon-theme`
If it's only about the additional button icons that are shipped with the RPi desktop build, either disable them with the setting I explained in OT or for the Raspbian build being installed via APT pinning:
```
cat << '_EOF_' > /etc/apt/preferences.d/raspbian-desktop
Package: pcmanfm libfm4 libfm-gtk4 lxpanel lxpanel-data
Pin: origin archive.raspberrypi.org
Pin-Priority: -1
_EOF_
```
